### ISSUE TITLE
MM interface update

### ISSUE THREAD

**Issue by SJShep** [micro-manager/mmdev-ThorlabsKinesis#2]
Micro-manager has updated the interface, from 70 to 71, could you build and release an update for the newer version?

**Comment by dpshepherd** [comment]
Hi @marktsuchida - this set of drivers is super useful for us and having it updated to the newer device interface would help. I'm happy to make an attempt at building this, but haven't setup the MM build environment before.

Do I just need to locally build mmCoreAndDevices (without private drivers)? And then build this repo?

Thanks!
Doug

**Comment by marktsuchida** [comment]
@SJShep @dpshepherd Thank you for reminding me.
I've uploaded a [build for 71](https://github.com/micro-manager/mmdev-ThorlabsKinesis/releases/tag/v20230207.71).

**Comment by dpshepherd** [comment]
Thank you @marktsuchida !!
